### ISSUE TITLE
Upgrade composer requirements

### ISSUE THREAD

**Issue by wpsmith** [woocommerce/woocommerce-sniffs#14]
`wp-coding-standards/wpcs` is now at `^2.3` and `dealerdirect/phpcodesniffer-composer-installer` is now at `^0.7`, so WooCommerce-Core sniffs need to updated.

**Comment by wpsmith** [comment]
See #13

**Comment by claudiosanches** [comment]
I just released `0.1.0`: https://packagist.org/packages/woocommerce/woocommerce-sniffs
