### ISSUE TITLE
Composer 2.2 "allow-plugins" config

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-sniffs#31]
I found out that Composer 2.2 introduces an `allow-plugins` setting, and without it `composer install` was failing...

```
{
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    }
}
```

[Some reference from the php code standards team](https://github.com/PHPCSStandards/composer-installer/issues/185#issuecomment-1193097022) (who obviously knows more than I do about this)

**Comment by ObliviousHarmony** [comment]
Thanks @helgatheviking.

I've set this configuration.
